const screens = [
  {
    id: "auth",
    title: "Authentication & Onboarding",
    owner: "Merchant",
    phase: "01",
    summary: "Google SSO entry, first-login provisioning, and blocked merchant states.",
    primary: "Continue with Google",
    secondary: "View API docs",
    metrics: [["SSO", "Google", "Primary login"], ["Merchant", "ACTIVE", "Default status"], ["Setup", "3/3", "Merchant, API key, vault"], ["Security", "AES", "Private key storage"]],
    side: "First login creates merchant profile, API key, and vault wallet before entering the dashboard.",
    table: { title: "Onboarding checklist", headers: ["Step", "State", "Notes"], rows: [["Create merchant", "SUCCESS", "Google profile mapped"], ["Generate API key", "SUCCESS", "Bearer token ready"], ["Generate vault wallet", "SUCCESS", "Encrypted private key"], ["Blocked state", "BLOCK", "Contact support shown"]] },
    form: "login"
  },
  {
    id: "dashboard",
    title: "Merchant Dashboard",
    owner: "Merchant",
    phase: "02",
    summary: "Operational overview for active transactions, tier usage, vault balance, and alerts.",
    primary: "Create API transaction",
    secondary: "Refresh",
    metrics: [["Active tx", "12/30", "Tier 5 usage"], ["Completed", "184", "Last 24 hours"], ["Vault USDT", "8,420", "Ready to withdraw"], ["Waiting sweep", "3", "Need BNB gas"]],
    side: "Dashboard keeps one primary CTA and sends all deep work to filtered transaction, wallet, or withdraw pages.",
    table: { title: "Recent activity", headers: ["UUID", "Status", "Amount", "Age"], rows: [["tx_8f21", "ACTIVE", "120 USDT", "18 min"], ["tx_7a10", "COMPLETED", "45 USDC", "2h 14m"], ["tx_6c55", "WAIT", "330 FDUSD", "1d"], ["tx_5f91", "SUCCESS", "Sweep done", "2d"]] },
    form: "alerts"
  },
  {
    id: "api",
    title: "API Key Management",
    owner: "Merchant",
    phase: "03",
    summary: "Copy, reveal, and reset Bearer API key with sensitive-action protection.",
    primary: "Copy API key",
    secondary: "Reset key",
    metrics: [["Auth", "Bearer", "Header format"], ["Key", "Masked", "Reveal on demand"], ["Reset", "Turnstile", "Bot protection"], ["Docs", "2 APIs", "Create and status"]],
    side: "Resetting key disables existing integrations. Confirmation requires Turnstile and explicit acknowledgement.",
    table: { title: "API examples", headers: ["Method", "Endpoint", "Purpose"], rows: [["POST", "/transaction/create", "Create clean payment wallet"], ["GET", "/transaction/{uuid}", "Fetch status and balances"]] },
    form: "api"
  },
  {
    id: "payment",
    title: "Transaction Create & Payment View",
    owner: "Merchant + Customer",
    phase: "04",
    summary: "Public payment state with address, QR, countdown, whitelist guidance, and received balances.",
    primary: "Copy address",
    secondary: "Open transaction",
    metrics: [["Status", "ACTIVE", "2 hour window"], ["Network", "BSC", "BNB Smart Chain"], ["Address", "Clean", "New wallet per transaction"], ["Tokens", "Whitelist", "Unsupported ignored"]],
    side: "Customer-facing payment view always shows text address fallback beside QR code for accessibility.",
    table: { title: "Received balances", headers: ["Token", "Amount", "Last transfer"], rows: [["USDT", "100.00", "0x91ab...12ce"], ["USDC", "24.50", "0x88fa...42dd"], ["FDUSD", "0.00", "No transfer yet"]] },
    form: "payment"
  },
  {
    id: "transactions",
    title: "Transaction List & Detail",
    owner: "Merchant",
    phase: "05",
    summary: "Filterable transaction table with detail summary, balances, blockchain transfers, and sweep state.",
    primary: "Export CSV",
    secondary: "Clear filters",
    metrics: [["Active", "12", "Accepting payments"], ["Completed", "1,284", "All-time"], ["Abandoned", "2", "Retry expired"], ["Filters", "GET", "Shareable URLs"]],
    side: "Rows open detail pages. Copy controls exist for UUID, wallet address, and tx hash.",
    table: { title: "Transactions", headers: ["UUID", "Status", "Wallet", "Total", "Expire at"], rows: [["tx_8f21", "ACTIVE", "0x7b...19a", "120 USDT", "11:42"], ["tx_7a10", "COMPLETED", "0x51...d22", "45 USDC", "09:14"], ["tx_6c55", "WAIT", "0x29...91c", "330 FDUSD", "Yesterday"]] },
    form: "filters"
  },
  {
    id: "wallet",
    title: "Vault & External Wallet",
    owner: "Merchant",
    phase: "06",
    summary: "Vault visibility, balance summary, BNB gas warning, and external wallet setup.",
    primary: "Save external wallet",
    secondary: "Copy vault",
    metrics: [["Vault", "1", "Per merchant"], ["Gas", "0.018 BNB", "Sufficient"], ["External", "Set", "Withdraw enabled"], ["Private key", "Hidden", "Never displayed"]],
    side: "External wallet changes are irreversible in practice and require confirmation plus Turnstile.",
    table: { title: "Vault balances", headers: ["Token", "Amount", "Status"], rows: [["BNB", "0.018", "SUCCESS"], ["USDT", "8,420.00", "SUCCESS"], ["USDC", "980.20", "SUCCESS"], ["CAKE", "42.00", "SUCCESS"]] },
    form: "wallet"
  },
  {
    id: "withdraw",
    title: "Withdraw Flow",
    owner: "Merchant",
    phase: "07",
    summary: "Withdraw amount/all from vault to external wallet with gas readiness and confirmation.",
    primary: "Request withdraw",
    secondary: "Withdraw all",
    metrics: [["Mode", "Amount/All", "Segmented control"], ["Queue", "PENDING", "Worker pickup"], ["Gas check", "Required", "Vault pays BNB"], ["Turnstile", "Enabled", "Sensitive action"]],
    side: "The confirmation modal repeats token, amount, wallet, and irreversible blockchain warning.",
    table: { title: "Withdraw history", headers: ["Token", "Amount", "Status", "Tx hash"], rows: [["USDT", "300.00", "PROCESSING", "Pending"], ["USDC", "100.00", "SUCCESS", "0x18cd...be9"], ["CAKE", "12.00", "FAILED", "Missing BNB"]] },
    form: "withdraw"
  },
  {
    id: "admin-crud",
    title: "Admin Merchant & Token Management",
    owner: "Admin",
    phase: "08",
    summary: "Merchant CRUD, tier changes, block/active actions, and token whitelist management.",
    primary: "Create token",
    secondary: "Filter merchants",
    metrics: [["Merchants", "128", "Multi merchant"], ["Blocked", "4", "Manual admin action"], ["Tokens", "7", "Whitelisted"], ["Tier max", "100", "Active tx limit"]],
    side: "Admin can manage token whitelist. Token disable needs impact confirmation for future processing.",
    table: { title: "Merchants", headers: ["Merchant", "Tier", "Status", "Active tx"], rows: [["Acme Shop", "5", "ACTIVE", "12"], ["North Labs", "2", "ACTIVE", "3"], ["Risky Store", "0", "BLOCK", "0"]] },
    form: "admin"
  },
  {
    id: "monitoring",
    title: "Monitoring",
    owner: "Admin",
    phase: "09",
    summary: "Transaction, sweep, withdraw, worker heartbeat, queue depth, and failure monitoring.",
    primary: "Retry selected",
    secondary: "Pause refresh",
    metrics: [["Blocks", "2,948", "Observed today"], ["Sweep wait", "18", "Mostly gas"], ["Withdraw fail", "3", "Needs action"], ["Heartbeat", "3/3", "Workers alive"]],
    side: "Auto-refresh must be pausable and never steal focus. Charts include text summaries.",
    table: { title: "Worker queue", headers: ["Worker", "Status", "Queue", "Last heartbeat"], rows: [["blockchain-listener", "SUCCESS", "0", "8s ago"], ["sweep-worker", "WAIT", "18", "12s ago"], ["withdraw-worker", "SUCCESS", "2", "10s ago"]] },
    form: "monitoring"
  },
  {
    id: "logs",
    title: "System Logs, Security & Health",
    owner: "Admin",
    phase: "10",
    summary: "System logs, security events, Cloudflare coverage, and Docker Compose service health.",
    primary: "Copy filtered URL",
    secondary: "Export logs",
    metrics: [["Services", "7/7", "Healthy"], ["Turnstile", "On", "Sensitive actions"], ["WAF", "On", "Cloudflare"], ["Errors", "2", "Last hour"]],
    side: "Sensitive values are masked by default. Long log messages wrap on mobile.",
    table: { title: "Security events", headers: ["Time", "Severity", "Service", "Event"], rows: [["12:08", "SUCCESS", "fastapi", "Google SSO login"], ["12:11", "WARN", "turnstile", "Withdraw challenge failed"], ["12:18", "DANGER", "api", "Blocked merchant key used"]] },
    form: "logs"
  }
];

